# Generated by Django 3.2 on 2021-05-05 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_introduction',
            new_name='comment_content',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='新用户<function now at 0x000001D28898F9D8>', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(default='https://img.imgdb.cn/item/60929de2d1a9ae528fbc42d5.png', max_length=200, verbose_name='头像url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_hot_rate',
            field=models.IntegerField(verbose_name='点赞数量'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('已注销'), to=settings.AUTH_USER_MODEL, verbose_name='作者id'),
        ),
    ]
