# Generated by Django 3.2 on 2021-05-05 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210505_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_photo_url',
            field=models.CharField(default='https://img.imgdb.cn/item/60929de2d1a9ae528fbc42d5.png', max_length=200, verbose_name='头像url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者id'),
        ),
    ]
