# Generated by Django 3.2 on 2021-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organize',
            field=models.CharField(default='未知', max_length=200, verbose_name='所在组织'),
            preserve_default=False,
        ),
    ]
