# Generated by Django 3.2 on 2021-05-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_organize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organize',
            new_name='academy',
        ),
    ]
