# Generated by Django 3.2 on 2021-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_organize_user_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academy',
            field=models.CharField(default='未选择', max_length=200, verbose_name='所在组织'),
        ),
    ]
