# Generated by Django 3.2 on 2021-05-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='StudentID',
            field=models.BigIntegerField(default=0, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(default='https://img.imgdb.cn/item/60929de2d1a9ae528fbc42d5.png', max_length=200, verbose_name='头像url'),
        ),
    ]
