# Generated by Django 3.2 on 2021-05-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210520_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='StudentID',
            field=models.BigIntegerField(unique=True, verbose_name='学号'),
        ),
    ]
